"""Append comment and description fields

Revision ID: e1582b5763b3
Revises: 16808f69f53a
Create Date: 2024-05-05 18:58:24.144879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1582b5763b3'
down_revision: Union[str, None] = '16808f69f53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personaltable', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('personaltable', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personaltable', 'description')
    op.drop_column('personaltable', 'comment')
    # ### end Alembic commands ###
